### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by meabed** [flash-oss/graphql-upload-minimal#26]
Thank you for making this.
Typescript is wrong? 
```TS2305: Module '"graphql-upload-minimal"' has no exported member 'graphqlUploadExpress'.```
It would be great to support it.

Thank you 👍

**Comment by koresar** [comment]
Hello

We deliberately removed this typing because we don't want to force everyone
to install the "express" framework. Many people run this library in koa,
hapi, serverless, etc. It's unreasonable to ask everyone installing an
entire framework just to make some people TypeScript compiler happy.

If you know how we make your TypeScript happy WITHOUT putting "express" to
the module dependencies, we're happy to accept your pull request.

Cheers

**Comment by koresar** [comment]
Or, you're saying, our README is wrong?

> `const { graphqlUploadExpress } = require("graphql-upload-minimal");`

**Comment by meabed** [comment]
Thank you @koresar :) yes I mean the typing of this express or koa exports are not defined, so typescript fails. 
It would be great to add all the exports types from lib.
I didn't mean installing express or koa.

Thank you

**Comment by meabed** [comment]
@koresar I have forked the project here and convert it to typescript and I use it my code and works well with types.
Maybe it could help in adding the types here https://github.com/meabed/graphql-upload-ts

Thank you

**Comment by koresar** [comment]
@meabed Oh, mate. That's a great work by you!
I wish we could just submit the above as a PR to this module. But I guess it's too late.

I wish you all the best maintaining your module. TS is the most popular language currently.

If people would be asking for TS typings I'll refer them to you.

Also, I'd recommend to submit your fork to this list: https://github.com/jaydenseric/graphql-multipart-request-spec#server

Cheers
