### ISSUE TITLE
Integration with Apollo Server

### ISSUE THREAD

**Issue by bazaglia** [flash-oss/graphql-upload-minimal#5]
Hey! I'm using the Apollo Server (apollo-server-lambda) and I can see internally they are already integrating with graphql-upload:

```javascript
const fileUploadHandler = (next: Function) => {
    const contentType = (
      event.headers['content-type'] || event.headers['Content-Type'] || ''
    ).toLowerCase();
    if (contentType.startsWith('multipart/form-data')
      && typeof processFileUploads === 'function') {
      const request = new FileUploadRequest() as IncomingMessage;
      request.push(
        Buffer.from(
          <any>event.body,
          event.isBase64Encoded ? 'base64' : 'ascii'
        )
      );
      request.push(null);
      request.headers = event.headers;
      processFileUploads(request, response, this.uploadsConfig || {})
        .then(body => {
          event.body = body as any;
          return next();
        })
        .catch(error => {
          throw formatApolloErrors([error], {
            formatter: this.requestOptions.formatError,
            debug: this.requestOptions.debug,
          });
        });
    } else {
      return next();
    }
  };
```

In the code above extracted from Apollo Server, the `processFileUploads` function imports the `graphql-upload`and uses its `processRequest` method to reasign `event.body` to my lambda function.

From my understanding, `graphql-upload-minimal` is a fork that was written to work as a replacement for `graphql-upload`, being useful in serverless environments. The thing is though, Apollo Server is already handling that, and even though my lambda receives a base64 encoded event from ALB, in the resolver args, the file property already exposes to me a createReadStream method that worked just fine to create a buffer with the received chunks.

Given that:

• Are we supposed to fork apollo-server and remove everything related to graphql-upload before using this graphql-upload-minimal?
• If that is the case, what is the advantage of using this library?

**Comment by koresar** [comment]
Hi. Thanks for the questions!

First of all, no, this fork was not born from the serverless necessity. :) The README says: "needed something simpler which won't attempt doing any disk I/O". Because the original module does disk I/O. It streams every file via disk. You might never notice it though.

ApolloServer is massive and has limitation. It does not allow you to hold each resolver in a dedicated (separate) Lambda function. It wants you to have all your resolvers in a single Lambda function, or, alternatively, use their own schema federation product. Which is a complex development. (I could be wrong here, because my knowledge can be outdated in the modern fast pace world.)

However, `graphql-upload-minimal` can be used in Lambda as a separate function handling file upload resolver. Here is the entire Lambda function:
```js
module.exports.handle = function (event) {
  return require("graphql-upload-minimal")(event, null, { environment: "lambda" });
};
```

That's quite minimal, ain't it?

There is a simpler way to replace "graphql-upload" with "graphql-upload-minimal":
```sh
npm i override-require
```
```js
require("override-require")(m => m === "graphql-upload", require("graphql-upload-minimal"));
```

Also, please see "Differences" on top of the README.

Does that answer your question?
